// DeploymentsPage styles

const styles = {
  pageContainer: {
    padding: '24px',
    color: '#FFEBC8FF',
    background: 'linear-gradient(to bottom, #000044, #000022)',
    minHeight: 'calc(100vh - 64px)',  // Account for app bar height
    width: '100%',
    boxSizing: 'border-box',
  },
  pageHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '24px',
    background: '#141C2F',
    padding: '20px',
    borderRadius: '12px',
    border: '1px solid #FFC35BFF',
    maxWidth: '100%',
  },
  pageTitle: {
    fontSize: '24px',
    color: '#FF7A00',
    margin: 0,
  },
  pageIcon: {
    color: '#FF7A00',
  },
  organizationHeader: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: '24px',
    marginBottom: '16px',
    width: '100%',
  },
  organizationSection: {
    marginTop: '10px',
    width: '100%',
    textAlign: 'center',
  },
  addNewButton: {
    background: 'linear-gradient(135deg, #FF7A00, #FF4B00)',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: '50px',
    padding: '8px 20px',
    fontSize: '14px',
    fontWeight: 'bold',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    boxShadow: '0 2px 4px rgba(255, 122, 0, 0.3)',
  },
  addNewLink: {
    color: '#FF7A00',
    textDecoration: 'none',
    cursor: 'pointer',
    fontWeight: 'bold',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modalContainer: {
    background: '#141C2F',
    borderRadius: '12px',
    padding: '32px',
    width: '100%',
    maxWidth: '480px',
    margin: '20px',
    border: '1px solid #FFC35BFF',
  },
  modalTitle: {
    color: '#FFEBC8FF',
    fontSize: '28px',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: '8px',
  },
  modalSubtitle: {
    color: '#FFEBC8FF',
    textAlign: 'center',
    marginBottom: '32px',
    opacity: 0.8,
  },
  iconContainer: {
    background: 'linear-gradient(135deg, #FF7A00, #FF4B00)',
    borderRadius: '12px',
    padding: '24px',
    marginBottom: '24px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1px solid #FFC35BFF',
    boxShadow: '0 1px 5px #FFC35BFF',
  },
  circleIcon: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    background: '#FFFFFF',
    marginBottom: '8px',
  },
  iconLabel: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  formSection: {
    marginBottom: '32px',
  },
  formTitle: {
    color: '#FFEBC8FF',
    fontSize: '20px',
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: '16px',
  },
  formSubtitle: {
    color: '#FFEBC8FF',
    textAlign: 'center',
    marginBottom: '24px',
    opacity: 0.8,
  },
  inputLabel: {
    color: '#FFEBC8FF',
    fontSize: '14px',
    marginBottom: '8px',
    display: 'block',
  },
  input: {
    width: '100%',
    padding: '12px',
    borderRadius: '8px',
    border: '1px solid #FFC35BFF',
    background: 'transparent',
    color: '#FFEBC8FF',
    fontSize: '16px',
    outline: 'none',
    boxSizing: 'border-box',
  },
  buttonContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '16px',
  },
  cancelButton: {
    background: '#1A2337',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: '8px',
    padding: '12px 24px',
    fontSize: '14px',
    fontWeight: 'bold',
    cursor: 'pointer',
    flex: 1,
  },
  createButton: {
    background: 'linear-gradient(135deg, #FF7A00, #FF4B00)',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: '8px',
    padding: '12px 24px',
    fontSize: '14px',
    fontWeight: 'bold',
    cursor: 'pointer',
    flex: 1,
    boxShadow: '0 1px 3px rgba(255, 122, 0, 0.3)',
  },
  orgCard: {
    background: '#141C2F',
    borderRadius: '12px',
    padding: '24px',
    width: '100%',
    maxWidth: '420px',
    margin: '32px auto',
    border: '1px solid #FFC35BFF',
    color: '#FFEBC8FF',
    boxShadow: '0 1px 5px rgba(255, 195, 91, 0.2)',
  },
  orgCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  orgLogo: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  orgLogoIcon: {
    width: '48px',
    height: '48px',
    background: '#1A2337',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#FF7A00',
  },
  orgName: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#FFEBC8FF',
  },
  separator: {
    height: '1px',
    background: 'rgba(255, 195, 91, 0.3)',
    margin: '16px 0',
    width: '100%',
  },
  messageBox: {
    textAlign: 'center',
    padding: '12px 0',
    color: '#FFEBC8FF',
    opacity: 0.8,
  },
  deploymentLink: {
    color: '#FF7A00',
    textDecoration: 'none',
    cursor: 'pointer',
    fontWeight: 'bold',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 0',
    cursor: 'pointer',
    color: '#FFEBC8FF',
  },
  sectionTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '16px',
    fontWeight: 'bold',
  },
  userCount: {
    opacity: 0.8,
    marginLeft: '6px',
  },
  userRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '12px 0 12px 32px',
    borderBottom: '1px solid rgba(255, 195, 91, 0.1)',
  },
  userAvatar: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    backgroundColor: '#78350F',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#FFC35BFF',
    marginRight: '12px',
    border: '2px solid #FF7A00',
  },
  userName: {
    flex: 1,
    textAlign: 'left',
  },
  userEmail: {
    fontSize: '12px',
    opacity: 0.8,
    display: 'block',
    marginTop: '4px',
  },
  userRoles: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  roleItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    opacity: 0.8,
  },
  userActions: {
    marginLeft: '12px',
  },
  enrolledUserFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '12px 0 12px 32px',
    fontSize: '14px',
  },
  cardFooter: {
    textAlign: 'center',
    marginTop: '40px',
    fontSize: '12px',
    color: '#FFEBC8FF',
    opacity: 0.7,
  },
};

export default styles; 