// Helper function to get responsive styles based on viewport width
const getResponsiveStyles = (isMobile = false) => ({
  pageContainer: {
    padding: isMobile ? '12px' : '16px',
    color: '#FFEBC8FF',
    background: 'linear-gradient(to bottom, #000044, #000022)',
    minHeight: '100vh',
    width: '100%',
    boxSizing: 'border-box',
    overflowX: 'hidden',
  },
  settingsContainer: {
    background: '#141C2F',
    padding: isMobile ? '16px' : '24px',
    borderRadius: '12px',
    maxWidth: '900px',
    width: '95%',
    margin: '0 auto',
  },
  headerSection: {
    display: 'flex',
    alignItems: 'center',
    gap: isMobile ? '8px' : '12px',
    marginBottom: isMobile ? '16px' : '24px',
    flexWrap: isMobile ? 'wrap' : 'nowrap',
  },
  pageIcon: {
    color: '#FF7A00',
    background: '#1E50FF',
    padding: isMobile ? '6px' : '8px',
    borderRadius: '50%',
    minWidth: isMobile ? '18px' : '24px',
  },
  pageTitle: {
    fontSize: isMobile ? '20px' : '24px',
    color: '#FF7A00',
    margin: 0,
  },
  selectSection: {
    marginBottom: isMobile ? '16px' : '24px',
    position: 'relative',
    width: isMobile ? '100%' : 'auto',
  },
  selectLabel: {
    position: 'absolute',
    top: '-10px',
    left: '12px',
    color: '#FFEBC8FF',
    fontSize: isMobile ? '12px' : '14px',
    background: '#141C2F',
    padding: '0 4px',
    zIndex: 1,
  },
  select: {
    width: '100%',
    background: '#1A2337',
    color: '#FFEBC8FF',
    padding: isMobile ? '10px' : '12px',
    borderRadius: '8px',
    border: '1px solid #FFC35BFF',
    fontSize: isMobile ? '14px' : '16px',
    cursor: 'pointer',
    outline: 'none',
  },
  organizationSection: {
    width: '95%',
    maxWidth: '900px',
    margin: isMobile ? '16px auto 0' : '24px auto 0',
  },
  organizationHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: isMobile ? 'flex-start' : 'center',
    marginBottom: isMobile ? '12px' : '16px',
    width: '100%',
    flexWrap: isMobile ? 'wrap' : 'nowrap',
    flexDirection: isMobile ? 'column' : 'row',
    gap: isMobile ? '8px' : '0',
  },
  sectionTitle: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: isMobile ? '6px' : '8px',
    minWidth: 0,
    flex: 1,
    fontSize: isMobile ? '14px' : '16px',
  },
  sectionText: {
    whiteSpace: 'normal',
    overflow: 'visible',
    textOverflow: 'clip',
    lineHeight: '1.4',
    paddingTop: '2px',
    fontSize: isMobile ? '14px' : '16px',
  },
  sectionCount: {
    opacity: 0.8,
    marginLeft: '6px',
    whiteSpace: 'nowrap',
    fontSize: isMobile ? '12px' : '14px',
  },
  sectionActions: {
    display: 'flex',
    alignItems: 'center',
    gap: isMobile ? '8px' : '12px',
    marginLeft: isMobile ? '0' : '12px',
    marginTop: isMobile ? '8px' : '0',
  },
  addButton: {
    background: 'linear-gradient(135deg, #FF7A00, #FF4B00)',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: '8px',
    padding: isMobile ? '6px 12px' : '8px 16px',
    fontSize: isMobile ? '11px' : '12px',
    fontWeight: 'bold',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    marginLeft: isMobile ? '0' : '12px',
    whiteSpace: 'nowrap',
    minWidth: 'fit-content',
    alignSelf: isMobile ? 'flex-start' : 'auto',
  },
  description: {
    color: '#FFEBC8FF',
    fontSize: isMobile ? '14px' : '16px',
    textAlign: 'left',
    paddingLeft: '0',
    marginLeft: '0'
  },
  orgCard: {
    background: '#141C2F',
    borderRadius: '12px',
    padding: isMobile ? '16px' : '24px',
    width: '95%',
    maxWidth: '900px',
    margin: isMobile ? '16px auto 0' : '24px auto 0',
    border: '1px solid #FFC35BFF',
    color: '#FFEBC8FF',
    boxSizing: 'border-box',
  },
  orgCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: isMobile ? '16px' : '20px',
    flexWrap: isMobile ? 'wrap' : 'nowrap',
  },
  orgLogo: {
    display: 'flex',
    alignItems: 'center',
    gap: isMobile ? '8px' : '12px',
    flex: 1,
    minWidth: 0,
  },
  orgLogoIcon: {
    width: isMobile ? '36px' : '48px',
    height: isMobile ? '36px' : '48px',
    background: '#1A2337',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#FF7A00',
    flexShrink: 0,
  },
  orgName: {
    fontSize: isMobile ? '16px' : '20px',
    fontWeight: 'bold',
    color: '#FFEBC8FF',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  separator: {
    height: '1px',
    background: 'rgba(255, 195, 91, 0.3)',
    margin: isMobile ? '12px 0' : '16px 0',
    width: '100%',
  },
  messageBox: {
    textAlign: 'center',
    padding: isMobile ? '8px 0' : '12px 0',
    color: '#FFEBC8FF',
    opacity: 0.8,
    fontSize: isMobile ? '14px' : '16px',
  },
  deploymentLink: {
    color: '#FF7A00',
    textDecoration: 'none',
    cursor: 'pointer',
    fontWeight: 'bold',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: isMobile ? '6px 0' : '8px 0',
    cursor: 'pointer',
    color: '#FFEBC8FF',
    minWidth: 0,
  },
  userCount: {
    opacity: 0.8,
    marginLeft: '6px',
    fontSize: isMobile ? '12px' : '14px',
  },
  userRow: {
    display: 'flex',
    alignItems: 'flex-start',
    padding: isMobile ? '6px 10px' : '8px 16px',
    gap: isMobile ? '8px' : '12px',
    position: 'relative',
    minHeight: isMobile ? '40px' : '48px',
    width: '100%',
  },
  userAvatar: {
    width: isMobile ? '28px' : '32px',
    height: isMobile ? '28px' : '32px',
    borderRadius: '50%',
    backgroundColor: '#78350F',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#FFC35BFF',
    flexShrink: 0,
    fontSize: isMobile ? '12px' : '14px',
    fontWeight: '500',
  },
  userName: {
    flex: '1',
    display: 'flex',
    flexDirection: 'column',
    gap: isMobile ? '2px' : '4px',
    alignItems: 'flex-start',
    paddingRight: isMobile ? '24px' : '32px',
    minWidth: 0,
  },
  userEmail: {
    fontSize: isMobile ? '12px' : '14px',
    color: '#FFEBC8FF',
    display: 'block',
    textAlign: 'left',
    width: '100%',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  userRoles: {
    display: 'flex',
    flexDirection: 'column',
    gap: isMobile ? '2px' : '4px',
    alignItems: 'flex-start',
    width: '100%',
  },
  roleItem: {
    display: 'flex',
    alignItems: 'center',
    gap: isMobile ? '4px' : '6px',
    fontSize: isMobile ? '10px' : '12px',
    color: 'rgba(255, 235, 200, 0.6)',
    padding: '0',
  },
  userActions: {
    position: 'absolute',
    right: isMobile ? '8px' : '16px',
    top: '50%',
    transform: 'translateY(-50%)',
  },
  enrolledUserFooter: {
    display: 'flex',
    padding: isMobile ? '8px 0 8px 24px' : '12px 0 12px 32px',
    fontSize: isMobile ? '12px' : '14px',
    alignItems: 'right',
  },
  cardFooter: {
    textAlign: 'center',
    marginTop: isMobile ? '24px' : '40px',
    fontSize: isMobile ? '11px' : '12px',
    color: '#FFEBC8FF',
    opacity: 0.7,
  },
  pageFooter: {
    textAlign: 'center',
    marginTop: isMobile ? '24px' : '40px',
    marginBottom: isMobile ? '16px' : '24px',
    fontSize: isMobile ? '11px' : '12px',
    color: '#FFEBC8FF',
    opacity: 0.7,
    width: '95%',
    maxWidth: '900px',
    margin: isMobile ? '24px auto 16px' : '40px auto 24px',
  },
});

// Export both the responsive styles function and the default desktop styles
const styles = getResponsiveStyles(false);

// Add the responsive styles function to the exported object
styles.getResponsiveStyles = getResponsiveStyles;

export default styles; 