const styles = {
  pageContainer: {
    padding: '16px',
    color: '#FFEBC8FF',
    background: 'linear-gradient(to bottom, #000044, #000022)',
    minHeight: '100vh',
    width: '100%',
    boxSizing: 'border-box',
  },
  settingsContainer: {
    background: '#141C2F',
    padding: '24px',
    borderRadius: '12px',
    maxWidth: '900px',
    width: '95%',
    margin: '0 auto',
  },
  headerSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '24px',
  },
  pageIcon: {
    color: '#FF7A00',
    background: '#1E50FF',
    padding: '8px',
    borderRadius: '50%',
  },
  pageTitle: {
    fontSize: '24px',
    color: '#FF7A00',
    margin: 0,
  },
  selectSection: {
    marginBottom: '24px',
    position: 'relative',
  },
  selectLabel: {
    position: 'absolute',
    top: '-10px',
    left: '12px',
    color: '#FFEBC8FF',
    fontSize: '14px',
    background: '#141C2F',
    padding: '0 4px',
    zIndex: 1,
  },
  select: {
    width: '100%',
    background: '#1A2337',
    color: '#FFEBC8FF',
    padding: '12px',
    borderRadius: '8px',
    border: '1px solid #FFC35BFF',
    fontSize: '16px',
    cursor: 'pointer',
    outline: 'none',
  },
  organizationSection: {
    width: '95%',
    maxWidth: '900px',
    margin: '24px auto 0',
  },
  organizationHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
    width: '100%',
    flexWrap: 'nowrap',
  },
  sectionTitle: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '8px',
    minWidth: 0,
    flex: 1,
    fontSize: '16px',
  },
  sectionText: {
    whiteSpace: 'normal',
    overflow: 'visible',
    textOverflow: 'clip',
    lineHeight: '1.4',
    paddingTop: '2px',
  },
  sectionCount: {
    opacity: 0.8,
    marginLeft: '6px',
    whiteSpace: 'nowrap',
  },
  sectionActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginLeft: '12px',
  },
  addButton: {
    background: 'linear-gradient(135deg, #FF7A00, #FF4B00)',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: '8px',
    padding: '8px 16px',
    fontSize: '12px',
    fontWeight: 'bold',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    marginLeft: '12px',
    whiteSpace: 'nowrap',
    minWidth: 'fit-content',
  },
  description: {
    color: '#FFEBC8FF',
    fontSize: '16px',
    textAlign: 'left',
    paddingLeft: '0',
    marginLeft: '0'
  },
  orgCard: {
    background: '#141C2F',
    borderRadius: '12px',
    padding: '24px',
    width: '95%',
    maxWidth: '900px',
    margin: '24px auto 0',
    border: '1px solid #FFC35BFF',
    color: '#FFEBC8FF',
    boxSizing: 'border-box',
  },
  orgCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  orgLogo: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  orgLogoIcon: {
    width: '48px',
    height: '48px',
    background: '#1A2337',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#FF7A00',
  },
  orgName: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#FFEBC8FF',
  },
  separator: {
    height: '1px',
    background: 'rgba(255, 195, 91, 0.3)',
    margin: '16px 0',
    width: '100%',
  },
  messageBox: {
    textAlign: 'center',
    padding: '12px 0',
    color: '#FFEBC8FF',
    opacity: 0.8,
  },
  deploymentLink: {
    color: '#FF7A00',
    textDecoration: 'none',
    cursor: 'pointer',
    fontWeight: 'bold',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 0',
    cursor: 'pointer',
    color: '#FFEBC8FF',
    minWidth: 0,
  },
  userCount: {
    opacity: 0.8,
    marginLeft: '6px',
  },
  userRow: {
    display: 'flex',
    alignItems: 'flex-start',
    padding: '8px 16px',
    gap: '12px',
    position: 'relative',
    minHeight: '48px',
    width: '100%',
  },
  userAvatar: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    backgroundColor: '#78350F',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#FFC35BFF',
    flexShrink: 0,
    fontSize: '14px',
    fontWeight: '500',
  },
  userName: {
    flex: '1',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    alignItems: 'flex-start',
    paddingRight: '32px',
  },
  userEmail: {
    fontSize: '14px',
    color: '#FFEBC8FF',
    display: 'block',
    textAlign: 'left',
    width: '100%',
  },
  userRoles: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    alignItems: 'flex-start',
    width: '100%',
  },
  roleItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    color: 'rgba(255, 235, 200, 0.6)',
    padding: '0',
  },
  userActions: {
    position: 'absolute',
    right: '16px',
    top: '50%',
    transform: 'translateY(-50%)',
  },
  enrolledUserFooter: {
    display: 'flex',
    padding: '12px 0 12px 32px',
    fontSize: '14px',
    alignItems: 'right',
  },
  cardFooter: {
    textAlign: 'center',
    marginTop: '40px',
    fontSize: '12px',
    color: '#FFEBC8FF',
    opacity: 0.7,
  },
  pageFooter: {
    textAlign: 'center',
    marginTop: '40px',
    marginBottom: '24px',
    fontSize: '12px',
    color: '#FFEBC8FF',
    opacity: 0.7,
    width: '95%',
    maxWidth: '900px',
    margin: '40px auto 24px',
  },
};

export default styles; 